//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empData
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public long mobile { get; set; } //big int
        public bool Flag { get; set; }
        public Nullable<System.DateTime> datetime { get; set; } //datatype
    }
}
